spring:
 profiles:
  active:
  - dev
---
spring:
 profiles: dev   #开发环境
 application:
  name: clouddemo-config-dzt-dev
---
spring:
 profiles: test  #测试环境
 application:
  name: clouddemo-config-dzt-test
                                    